apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mock-aws-admins
subjects:
  - kind: User
    name: arn:aws:iam::180789647333:user/eksadmin1
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: arn:aws:iam::180789647333:user/eksadmin2
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonly
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mock-aws-readonly
subjects:
  - kind: User
    name: arn:aws:iam::180789647333:user/eksreadonly
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: readonly
  apiGroup: rbac.authorization.k8s.io
